site_name: Gamedev-org
nav:
  - Home: index.md
  - About: about.md
  - Front-end:
     - Writing your docs: about.md
     - Styling your docs: about.md
  - Back-end:
     - License: about.md
     - Release Notes: about.md
theme:
  name: materia
  nav_style: light