#site_name: gamedev.space
#nav:
#  - Home: index.md
#  - Front-end:
#      # 客户端文章列表
#      - ET-Demo: Front-end/ET/ET-Demo.md
#      - Writing your docs: Front-end/index.md
#  - Back-end:
#      # 服务器文章列表
#      - Writing your docs: Back-end/index.md
#      - Styling your docs: Back-end/index2.md
#  - Other:
#      # CI/CD文章列表 
#      - 自动化部署Mkdocs: Other/自动化部署Mkdocs.md
#      - 工具链: Other/工具链.md
#  - About: help.md
#
#markdown_extensions:
#  - toc:
#      permalink: "#"
#      baselevel: 2
#theme:
#  name: materia
#  nav_style: light
  
  
  
site_name: Gamedev.space
site_url: https://gamedev-org.github.io/
site_description: Game Dev Project documentation.
site_author: Gamedev.space Team

repo_url: https://github.com/Gamedev-org/gamedev-org.github.io
edit_uri: ""

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home: index.md
  - Front-end:
      # 客户端文章列表
      - ET-Demo: Front-end/ET/ET-Demo.md
      - Writing your docs: Front-end/index.md
  - Back-end:
      # 服务器文章列表
      - Writing your docs: Back-end/index.md
      - Styling your docs: Back-end/index2.md
  - Other:
      # CI/CD文章列表 
      - 自动化部署Mkdocs: Other/自动化部署Mkdocs.md
      - 工具链: Other/工具链.md
  - About: help.md

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - def_list
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs

copyright: Copyright &copy; 2020 | Maintained by the <a href="https://gamedev-org.github.io/">Gamedev.space Team</a>.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
  - search
