# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    # Python & Pip Installer
    - uses: actions/setup-python@v1
    - uses: dschep/install-pipenv-action@v1
    - name: prepare build env
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "longshilin"
        git config --global user.email "longshilin@users.noreply.github.com"
        pip install mkdocs
        pip install mkdocs-bootstrap
        pip install mkdocs-bootswatch
    - name: build 
      env:
        PULL_BRANCH: master
        PUSH_BRANCH: gh-pages
      run: |
        git clone --branch ${PULL_BRANCH} git@github.com:Gamedev-org/gamedev-org.github.io.git ${PULL_BRANCH};
        cd ${PULL_BRANCH};
        mkdocs build;
        git clone --branch ${PUSH_BRANCH} git@github.com:Gamedev-org/gamedev-org.github.io.git ../${PUSH_BRANCH}; 
        cd ../${PUSH_BRANCH};
        cp -f ../${PULL_BRANCH}/site/* .;
        git add *; git commit -a -m "Site updated：`date`"; git push -f;
